name: LoganJamesLiving
favicon: null
layout_spectrum: 0
typography_spectrum: 0.22528
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00c6b7'
    - '#ff8e33'
    - '#5dddd4'
    - '#b9f1eb'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
